config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => "households#index"

  devise_for :users

  resources :members

  get 'transactions(.:format)', :controller => :transactions, :action => :all_households, :as => :all_transactions
  get 'monthly_reports', :controller => :monthly_reports, :action => :index, :as => 'monthly_reports'
  get 'test_exception', :controller => :test_exception, :action => :test_exception

  resources :households do
    resources :transactions
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :except => :all_households do
     @household = Household.find(params[:household_id])
  end

  def all_households
    @transactions = Transaction.includes(:household => [:members]).order("id DESC").paginate(:page => params[:page], :per_page => 30)

    respond_to do |format|
      format.html # index.html.erb
      format.csv  { render :csv => @transactions }
    end
  end

  # GET /households/:id/transactions
  # GET /households/:id/transactions.xml
  def index
     @transactions = Transaction.for_household(params[:household_id])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions }
      format.csv  { render :csv => @transactions }
    end
  end

  # GET /households/:id/transactions/1
  # GET /households/:id/transactions/1.xml
  def show
    @transaction = Transaction.for_household(params[:household_id]).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /households/:id/transactions/new
  # GET /households/:id/transactions/new.xml
  def new
    @transaction = Transaction.for_household(params[:household_id]).new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /households/:id/transactions/1/edit
  def edit
    @transaction = Transaction.for_household(params[:household_id]).find(params[:id])
  end

  # POST /households/:id/transactions
  # POST /households/:id/transactions.xml
  def create
    @transaction = Transaction.for_household(params[:household_id]).new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to(@household, :notice => 'Household transaction was successfully created.') }
        format.xml  { render :xml => @transaction, :status => :created, :location => @transaction }
      else
        format.html { render :template => 'households/show' }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /households/:id/transactions/1
  # PUT /households/:id/transactions/1.xml
  def update
    @transaction = Transaction.for_household(params[:household_id]).find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to(household_transaction_url(@household, @transaction), :notice => 'Household transaction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /households/:id/transactions/1
  # DELETE /households/:id/transactions/1.xml
  def destroy
    raise Exception.new("deleting transactions is not allowed")
    @transaction = Transaction.for_household(params[:household_id]).find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to(household_transactions_url(@houshold)) }
      format.xml  { head :ok }
    end
  end
end

app/views/transactions/_create.html.erb
<h3>Make an investment or purchase</h3>
<%= form_for([household, transaction]) do |f| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this household from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <style type="text/css">
    #new_transaction input[type="submit"] {
      margin-top: 10px;
      margin-left: 285px;
    }
  </style>
  <fieldset style="float: left; margin-right: 40px;" class="field">
    <%= f.radio_button :credit, :true %>
    <%= f.label :credit_true, "Credit" %>
    <p class="help">investment, or credit adjustment</p>
    <%= f.radio_button :credit, :false %>
    <%= f.label :credit_false, "Debit" %>
    <p class="help">purchase, or debit adjustment</p>
  </fieldset>

  <div class="field">
    <%= f.label :amount %><br />
    $<%= f.text_field :amount, :size => 6 %>
  </div>

  <div class="field">
    <%= f.label :message, "Notes" %><br />
    <%= f.text_area :message, :rows => 4 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/_list.html.erb
<table>
  <tr>
    <th>Date</th>
    <th>Type</th>
    <th>Amount</th>
    <th>Message</th>
    <% if(print_household) %><th>Household</th><% end %>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr class="<%= cycle("even", "odd") %> <%= "void-transaction" if transaction.void? %>">
    <td><%= transaction.created_at %></td>
    <td>
    <%= "voided" if transaction.void? %>
    <%= transaction.credit ? 'investment' : 'purchase' %></td>
    <td class="money"><%= number_to_currency(transaction.amount) %></td>
    <td><%= transaction.message %></td>
    <% if(print_household) %>
      <td><%= link_to transaction.household.to_s, transaction.household %></td>
    <% end %>
    <td><%= link_to 'Edit', edit_household_transaction_path(transaction.household, transaction) %></td>
  </tr>
<% end %>
</table>

app/views/transactions/all_households.html.erb
<h1>All transactions</h1>

<% if @transactions.empty? %>
  <p>
  There are no transactions yet.
  </p>
<% else %>
  <%= render partial: 'list', locals: { transactions: @transactions, print_household: true } %>
  <%= will_paginate @transactions %>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction message</h1>

<%= form_for([@household, @transaction]) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
  <b>Created:</b> <%= @transaction.created_at %> <br />
  <b>Amount:</b> <%= number_to_currency(@transaction.amount) %>
  <%= @transaction.credit ? 'investment' : 'purchase' %>
  </p>
  
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.check_box :void %>
    <%= f.label :void, "Void transaction" %>
  </div>
  <div class="actions">
    <%= f.submit "update" %>
  </div>
<% end %>

<%= link_to 'Back', household_transactions_path(@household) %>

app/views/transactions/index.html.erb
<h1>Transactions</h1>
<p>for the <%= link_to "household of #{@household.to_s}", @household %></p>
<p>
  <strong>balance:</strong>
  <%= sprintf("$%.2f", @household.balance) %>
</p>
<% if @transactions.empty? %>
  <p>
  There are no transactions for this household yet.
  </p>
<% else %>
  <%= render partial: 'list', locals: { transactions: @transactions, print_household: false } %>
<% end %>
<br />

<%= link_to 'Back to household', @household %>

app/views/transactions/new.html.erb
<%= render :partial => 'create', :locals => {:transaction => @transaction, :household => @household} %>

app/views/transactions/show.html.erb
<p>
  <b>
  <%= @transaction.credit? ? "Investment" : "Purchase" %>
  for Household:</b>
  <%= @household %>
</p>

<p>
  <b>Date:</b>
  <%= @household.created_at %>

<p class="<%= "void-transaction" if @transaction.void? %>" >
  <b>Amount:</b>
  <%= number_to_currency(@transaction.amount) %> 
  <%= "(voided)" if @transaction.void? %>
</p>

<p>
  <b>Message:</b>
  <%= @transaction.message %>
</p>



<%= link_to 'Edit', edit_household_transaction_path(@household, @transaction) %> |
<%= link_to 'Back', household_transactions_path(@household) %>