config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => "households#index"

  devise_for :users

  resources :members

  get 'transactions(.:format)', :controller => :transactions, :action => :all_households, :as => :all_transactions
  get 'monthly_reports', :controller => :monthly_reports, :action => :index, :as => 'monthly_reports'
  get 'test_exception', :controller => :test_exception, :action => :test_exception

  resources :households do
    resources :transactions
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodlobby</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  <link href="/images/favicon.png" rel="icon" type="image/x-icon" />
</head>
<body>
  <% if current_user %>
    <%= link_to "sign out #{current_user}", destroy_user_session_url, :style => "float: right"%>
  <% end %>

<div id="wrapper">
  <% if current_user %>

    <ul class="navigation">
      <li><%= link_to_unless_current "households", root_url %></li>
      <li><%= link_to_unless_current "members", members_url %></li>
      <li><%= link_to_unless_current "monthly reports", monthly_reports_url %></li>
      <li><%= link_to_unless_current "transactions", all_transactions_url %></li>
    </ul>

  <% end %>

  <div id="content">
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "#{name}" %>
    <% end %>

    <%= yield %>
  </div>

  <div id="version_banner">
    Powered by <a href='http://www.ruby-lang.org/'>Ruby</a>, <a href="http://rubyonrails.org">Rails</a>, and <%= link_to 'this code', @revision_url %>.
  </div>

  <div id="footer">
    <div class="balloon">
      <div class="pointer">
        <span class="top"></span>
        <span class="bottom"></span>
      </div>
      <div class="content">
        We've spent <strong><span class="amount"><%= sprintf("$%d", @amount_purchased_this_week) %></span></strong> on <em>yummy</em> food this week<%= @amount_purchased_this_week == 0 ? " =(" : "!" -%>
      </div>
    </div>
  </div>
</div>
</body>
</html>