config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => "households#index"

  devise_for :users

  resources :members

  get 'transactions(.:format)', :controller => :transactions, :action => :all_households, :as => :all_transactions
  get 'monthly_reports', :controller => :monthly_reports, :action => :index, :as => 'monthly_reports'
  get 'test_exception', :controller => :test_exception, :action => :test_exception

  resources :households do
    resources :transactions
  end

end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :household
  has_many :household_membership_audits

  scope :with_households, -> { includes([{:household => :members}]) }

  scope :by_activity, ->(params) {
    include_active = params[:include_active]
    include_inactive = params[:include_inactive]

    if include_active
      if include_inactive
        where({})
      else
        where(:active => true)
      end
    else
      if include_inactive
        where(:active => false)
      else
        where({}) #if both are deselected, assume we want everybody
      end
    end
  }

  # The last member can't leave a household which has a non-zero balance, ensuring all money is accessible.
  validate do
    if(not new_record? and household_id_changed?)
      if(household_was.members == [self] and household_was.balance != 0)
        errors.add(:household, "You must transfer the old household's balance before removing it's last member.")
      end
    end
  end

  validates_presence_of :first_name, :last_name

  # Can we do this with something like:
  # words.split.inject(self.arel_table) do |members, word| 
  #   members.or(match('UPPER(first_name) LIKE UPPER(?) OR UPPER(last_name) LIKE UPPER(?)' , "%#{word}%", "%#{word}%"))
  # end
  def self.find_by_keywords(words)
    return Member.with_households if(words.strip.empty?)

    words.split.inject(Set.new()) do |matching_members, word|
      #Get all members who's first or last name matches
      matching_members + Member.with_households.where('UPPER(members.first_name) LIKE UPPER(?) OR UPPER(members.last_name) LIKE UPPER(?)' , "%#{word}%", "%#{word}%")
    end
  end

  def household_was
    if( household_id_was )
      Household.find(household_id_was)
    else
      nil
    end
  end

  before_validation do |member|
    # a member must always belong to a household.
    # If they aren't currently in a household, make a new one for them.
    member.build_household if member.household.nil?
  end

  # I would prefer a more general purpose auditing tool, but neither acts_as_audited nor vestal_versions
  # makes it easy to find both the addition of a member to a household and the removal.
  after_create do |member|
    HouseholdMembershipAudit.create!(:event => 'joined', :household_id => member.household_id, :member_id => member.id)
  end

  before_save do |member|
    # new record handled differently, in after_create,
    # because the member doesn't have an id before_create.
    # we can't generalize to "after_save" because the "member.household_was" is reset
    unless member.new_record?
      if member.household_id_changed?
        HouseholdMembershipAudit.create!(:event => 'joined', :household_id => member.household_id, :member_id => member.id)

        unless member.household_id_was.nil? #unless they weren't in a household before
          HouseholdMembershipAudit.create!(:event => 'left', :household_id => member.household_id_was, :member_id => member.id)
        end
      end
    end
  end

  def to_s
    if name != ''
      name
    elsif email.to_s != ''
      email.to_s
    else
      '(unknown member)'
    end
  end

  def name
    "#{first_name} #{last_name}".strip
  end

  #csv output
  comma do
    id
    last_name
    first_name
    household_id
    created_at
    updated_at
    phone1
    phone2
    address1
    address2
    city
    state
    zip
    notes
    active
    email
  end
end

# == Schema Information
#
# Table name: members
#
#  id           :integer(4)      not null, primary key
#  last_name    :string(255)
#  first_name   :string(255)
#  household_id :integer(4)
#  created_at   :datetime
#  updated_at   :datetime
#  phone1       :string(255)
#  phone2       :string(255)
#  address1     :string(255)
#  address2     :string(255)
#  city         :string(255)
#  state        :string(255)
#  zip          :string(255)
#  notes        :text
#  active       :boolean(1)      default(TRUE)
#  email        :string(255)
#  fm_id        :integer(4)
#

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.xml
  def index
    @members = Member.by_activity(:include_active => params[:active], :include_inactive => params[:inactive])

    if params[:search]
      @members = @members.find_by_keywords(params[:search])
    else
      @members = @members.with_households.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @members }
      format.csv { render :csv => @members }
    end
  end

  # GET /members/1
  # GET /members/1.xml
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @member }
    end
  end

  # GET /members/new
  # GET /members/new.xml
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.xml
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to(@member, :notice => 'Member was successfully created.') }
        format.xml  { render :xml => @member, :status => :created, :location => @member }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @member.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.xml
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to(@member, :notice => 'Member was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @member.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.xml
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to(members_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, :size => 20 %>

      <span style="margin-right: 1em;"></span>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, :size => 20 %>
    </div>

    <div class="field">
      <%= f.label :active, "Active Member" %>
      <%= f.check_box :active %><br />
    </div>

    <div class="field">
      <%= f.label :email, "Email" %>
      <%= f.text_field :email, :size=>25 %>
    </div>

    <div class="field">
      <%= f.label :phone1, "Phone 1" %>
      <%= f.text_field :phone1, :size=>15 %>

      <%= f.label :phone2, "Phone 2" %>
      <%= f.text_field :phone2, :size=>15 %>
    </div>
    <div class="field">
      <%= f.label :address1, "Address Line 1" %><br />
      <%= f.text_field :address1, :size=>50 %>
    </div>
    <div class="field">
      <%= f.label :address2, "Address Line 2" %><br />
      <%= f.text_field :address2, :size=>50 %>
    </div>
    <div class="field">
      <%= f.label :city, "City" %>
      <%= f.text_field :city, :size=>20 %>,
      <%= f.label :state, "State" %>
      <%= f.text_field :state, :size=>2 %>
      <%= f.label :zip, "Zip" %>
      <%= f.text_field :zip, :size=>9 %>
    </div>

    <%= f.label :household_id %>
    <% if @member.household %>
      <ol>
      <% @member.household.members.each do |m| %>
        <li><%= link_to m.name, m %></li>
      <% end %>
      </ol>
    <% end %>
    <%= f.collection_select(:household_id, Member.all, :household_id, :to_s, {:include_blank => 'Put this member in a new household'} ) %>
    <% if @member.new_record? %>
      <p class="help">Add this member to which household?</p>
    <% else %>
      <p class="help">Move this member to a different household?</p>
    <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<%= form_tag members_path, :method => 'get', :id => 'filter' do %>
  <fieldset>
    <%= label_tag :active %>
    <%= check_box_tag :active, :active, params[:active] %>
    <%= label_tag :inactive %>
    <%= check_box_tag :inactive, :inactive, params[:inactive] %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Filter", :name => nil %>
  </fieldset>
<% end %>

<h1>Members</h1>
<% if @members.empty? %>
 <p>There are no members matching your criteria.</p>
<% else %>
<table id="members">
  <tr>
    <th>Last name</th>
    <th>First name</th>
    <th>Household</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr class="<%= cycle("even", "odd") %>">
    <td><%= member.last_name %></td>
    <td><%= member.first_name %></td>
    <td><%= link_to member.household.to_s, member.household %></td>
    <td><%= link_to 'Show', member, :class => "action" %></td>
    <td><%= link_to 'Edit', edit_member_path(member), :class => "action" %></td>
  </tr>
<% end %>

</table>
<% end %>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<h1 style="float: left;">
  <%= @member.name %>
</h1>

<ul class="navigation actions">
  <li>
  (<%= link_to 'Edit member info', edit_member_path(@member) %>)
  </li>
</ul>

<br style="clear: both;" />

<p>
<%= @member.active ? "Active" : "Inactive" %> Member
</p>

<p>
<%= link_to "view household", @member.household %>
</p>

<!-- TODO: add optional display to all lines -->
<div>
<% if @member.email.present? %>
  <b>Email:</b> <%= @member.email %><br />
<% end %>

<% if @member.phone1.present? %>
  <b>Primary phone:</b> <%= @member.phone1 %><br />
<% end %>

<% if @member.phone2.present? %>
  <b>Secondary phone:</b> <%= @member.phone2 %><br />
<% end %>

<b>Address</b><br />
<%= @member.address1 %><br />
<% if @member.address2 != '' %>
  <%= @member.address2 %><br />
<% end %>
<%= "#{@member.city}, #{@member.state} #{@member.zip}" %><br />

</div>


<%= link_to 'Back', members_path %>