config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => "households#index"

  devise_for :users

  resources :members

  get 'transactions(.:format)', :controller => :transactions, :action => :all_households, :as => :all_transactions
  get 'monthly_reports', :controller => :monthly_reports, :action => :index, :as => 'monthly_reports'
  get 'test_exception', :controller => :test_exception, :action => :test_exception

  resources :households do
    resources :transactions
  end

end

app/models/household.rb
class Household < ActiveRecord::Base
  has_many :members
  has_many :transactions
  has_many :household_membership_audits

  #OPTIMIZE this horse shit.
  def self.id_by_keywords(words)
    return self.all if(words.strip.empty?)

    words.split.inject(Set.new()) do |members, word|
      #Get all members who's first or last name matches
      members + Member.where('UPPER(first_name) LIKE UPPER(?) OR UPPER(last_name) LIKE UPPER(?)' , "%#{word}%", "%#{word}%")
    end.map do |member|
      #Get their household ids
      member.household_id
    end.uniq #remove dupes.
  end

  scope :find_by_keywords, ->(words) { where('households.id in (?)', id_by_keywords(words)) }

  # All households with no members
  scope :empty, -> { joins('left outer join members on members.household_id = households.id').select('households.*').where('members.id is null') }
  scope :active, -> { joins(:members).where(:members => { :active => true }).includes(:members) }
  scope :by_recent_activity, -> { joins(:transactions).order('transactions.created_at DESC') }

  def to_s
    if members.empty?
      "empty household"
    else
      members.inject { |a,b| "#{a}, #{b}"}
    end
  end

  def credit! (amount)
    transactions.create!(:credit => true, :amount => amount)
    self.update_attribute(:balance, self.balance + amount)
  end

  def debit! (amount)
    transactions.create!(:credit => false, :amount => amount)
    self.update_attribute(:balance, self.balance - amount)
  end

  def last_transaction
    transactions.order('created_at').last
  end

  comma do
    id
    balance
    created_at
    updated_at
    notes
  end

end

# == Schema Information
#
# Table name: households
#
#  id         :integer(4)      not null, primary key
#  balance    :decimal(8, 2)   default(0.0)
#  created_at :datetime
#  updated_at :datetime
#  notes      :text
#  fm_id      :integer(4)
#

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
  # GET /households
  # GET /households.xml
  def index
    if params[:search]
      @households = Household.find_by_keywords(params[:search])
    else
      @households = Household.active.by_recent_activity
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @households }
      format.csv { render :csv => @households }
    end
  end

  # GET /households/1
  # GET /households/1.xml
  def show
    @household = Household.find(params[:id])
    @transaction = @household.transactions.new

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @household }
    end
  end

  # GET /households/new
  # GET /households/new.xml
  def new
    @household = Household.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @household }
    end
  end

  # GET /households/1/edit
  def edit
    @household = Household.find(params[:id])
  end

  # POST /households
  # POST /households.xml
  def create
    @household = Household.new(params[:household])

    respond_to do |format|
      if @household.save
        format.html { redirect_to(@household, :notice => 'Household was successfully created.') }
        format.xml  { render :xml => @household, :status => :created, :location => @household }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @household.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /households/1
  # PUT /households/1.xml
  def update
    @household = Household.find(params[:id])

    respond_to do |format|
      if @household.update_attributes(params[:household])
        format.html { redirect_to(@household, :notice => 'Household was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @household.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /households/1
  # DELETE /households/1.xml
  def destroy
    @household = Household.find(params[:id])
    @household.destroy

    respond_to do |format|
      format.html { redirect_to(households_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/households/_form.html.erb
<%= form_for(@household) do |f| %>
  <% if @household.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@household.errors.count, "error") %> prohibited this household from being saved:</h2>

      <ul>
      <% @household.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <h3>Household Members</h3>
  <ol>
    <% @household.members.each do |m| %>
      <li><%= link_to m, m %></li>
    <% end %>
  </ol>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/households/edit.html.erb
<h1>Editing household</h1>

<%= render 'form' %>

<%= link_to 'Show', @household %> |
<%= link_to 'Back', households_path %>

app/views/households/index.html.erb
<%= form_tag households_path, :method => 'get', :id => 'filter' do %>
  <fieldset>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Filter", :name => nil %>
  </fieldset>
<% end %>

<h1>Households</h1>
<% if @households.empty? %>
  <p>There are no active households matching your criteria.</p>
  <p>You could check the <%= link_to "members page", :members  %> to see if they exist as an inactive member.</p>
<% else %>
<table id="households">
  <tr>
    <th>Members</th>
    <th>Last seen</th>
    <th colspan=2 class="money">Balance</th>
  </tr>

<% @households.each do |household| %>
  <tr class="<%= cycle("even", "odd") %>">
    <td>
      <ol style="padding-top: 0px; padding-bottom: 0px; margin: 0px;">
      <% household.members.each do |member| %>
      	<li><%= member %></li>
      <% end %>
      </ol>
    </td>
    <td>
      <% if household.last_transaction %>
        <%= time_ago_in_words(household.last_transaction.created_at) %> ago
      <% else %>
        No financial record.
      <% end %>
    </td>
    <td class="money"><%= sprintf("$%.2f", household.balance) %></td>
    <td><%= link_to '+/-', household %></td>
  </tr>
<% end %>
</table>
<% end %>

app/views/households/new.html.erb
<h1>New household</h1>

<%= render 'form' %>

<%= link_to 'Back', households_path %>

app/views/households/show.html.erb
<h3>Financial</h3>
<b>Balance:</b> <%= sprintf("$%.2f", @household.balance) %>
[ <%= link_to 'View previous transactions', household_transactions_path(@household) %>]
<br />

<%= render :partial => 'transactions/create', :locals => {:household => @household, :transaction => @transaction }%>

<h3>Members</h3>
<ul id="members">
  <% @household.members.each do |m| %>
    <li><%= link_to m, m %></li>
  <% end %>
</ul>
<%= link_to 'add new member', new_member_path %>

<h3>History</h3>
<ul>
  <% @household.household_membership_audits.each do |audit| %>
  <li>
    <%= audit.member %> <%= audit.event %> the household on <%= audit.created_at %>
  </li>
<% end %>
</ul>

<%= link_to 'Back', households_path %>